# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagTracker',
            fields=[
                ('idtag_tracker', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_id', models.CharField(max_length=1024)),
                ('antenna', models.CharField(max_length=1024)),
                ('reader', models.CharField(max_length=1024)),
                ('status', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tag_tracker',
                'managed': False,
            },
        ),
    ]
